#!/usr/bin/perl -I/usr/local/sauron
#
# last -- utlity to display lastlog info
#
# Copyright (c) Timo Kokkonen <tjko@iki.fi>  2001-2003.
# $Id: last,v 1.9 2003/12/28 19:29:12 tjko Exp $
#
require 5;
use Getopt::Long;
use Sauron::DB;
use Sauron::Util;
use Sauron::BackEnd;
use Sauron::Sauron;

load_config();

##############################################

if (($ARGV[0] =~ /^--?h/)) {
  print "syntax: $0 [-h] [-num] [name]\n\n";
  exit(0);
}

if ($ARGV[0] =~ /^-(\d+)/) {
  $count_rule="$1";
  shift;
}

$user_rule="$ARGV[0]" if ($ARGV[0]);

db_connect();

$count=get_lastlog($count_rule,$user_rule,\@q);

printf "%-9s %5s %-39s %14s - %s\n",
        'User','SID','Host','Login','Logout';
print "-" x 78 . "\n";

for $j (0..($count-1)) {
  printf "%-9s %5d %-39s %14s - %s\n",
        $q[$j][0],$q[$j][1],$q[$j][2],$q[$j][3],$q[$j][4];
}



exit;

